"""Global_Literacy_and_GDP_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imS9c3wpQZNCxPuUwDeHJxoW_iWKtvEn

--------------------------------------------------------------------------------
# **Author** : ***Mohamed Halith M K***
## **Title**  : ***Global Literacy and GDP Analysis***
### ***GUVI Mini Projects - 2***
--------------------------------------------------------------------------------

# **Data Collection**
"""

#imported required libraries for this project
import pandas as pd
import numpy as np

# data collection

urls = {
    "adult": "https://ourworldindata.org/grapher/literacy-rate-adults.csv?v=1&csvType=full&useColumnShortNames=true",
    "youth": "https://ourworldindata.org/grapher/literacy-rate-of-young-men-and-women.csv?v=1&csvType=full&useColumnShortNames=true",
    "illiteracy": "https://ourworldindata.org/grapher/literate-and-illiterate-world-population.csv?v=1&csvType=full&useColumnShortNames=true",
    "gdp": "https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true",
    "schooling": "https://ourworldindata.org/grapher/literacy-rates-vs-average-years-of-schooling.csv?v=1&csvType=full&useColumnShortNames=true"
    }

datasets = {}

for name, url in urls.items():

    datasets[name] = pd.read_csv(
        url,
        storage_options={
            "User-Agent": "Our World In Data data fetch/1.0"
        }
    )

df_adult = datasets["adult"]
df_youth = datasets["youth"]
df_illiteracy = datasets["illiteracy"]
df_gdp = datasets["gdp"]
df_schooling = datasets["schooling"]

"""# **Data cleaning**

###**1. Standardize country & region names for merging**
"""

# List of dataframe-column pairs
datasets = [
    (df_adult, ["entity"]),
    (df_youth, ["entity", "owid_region"]),
    (df_illiteracy, ["entity"]),
    (df_gdp, ["entity", "owid_region"]),
    (df_schooling, ["entity", "owid_region"])
]

# Apply title case
for df, cols in datasets:
    for col in cols:
        df[col] = df[col].str.title()

"""###**2. Mereging Data Frames**"""

# df_literacy → Adult & Youth Literacy Rates
df_literacy = pd.merge(df_adult, df_youth, on=['entity', 'code', 'year'], how = 'left')

df_literacy

# df_gdp_schooling → GDP & Years of Schooling
df_gdp_schooling = pd.merge(df_gdp, df_schooling, on=['entity', 'code', 'year', 'owid_region'], how = 'left')

df_gdp_schooling

"""###**3. Rename column names for clarity**"""

# df_literacy
df_literacy.rename(columns={"entity" : "Country",
                            "code" : "Code",
                            "year" : "Year",
                            "adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99" : "Adult",
                            "youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m" : "Male",
                            "youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f" : "Female",
                            "owid_region" : "Region"},inplace=True)

df_literacy

# df_illiteracy
df_illiteracy.rename(columns={'entity': 'Country',
                                'illiteracy_rate' : 'Illiteracy_rate',
                                'literacy_rate' : 'Literacy_rate',
                                'year' : 'Year',
                                'code' : 'Code',}, inplace=True)

df_illiteracy

# df_gdp_schooling
df_gdp_schooling.rename(columns={"entity": "Country",
                                 "code" : "Code",
                                 "year" : "Year",
                                 "owid_region" : "Region",
                                 "ny_gdp_pcap_pp_kd" : "GDP",
                                 "literacy_rate" : "Literacy",
                                 "mf_youth_and_adults__15_64_years__average_years_of_education" : "Avg_yrs_schooling",
                                 "population_historical" : "Population"}, inplace=True)

df_gdp_schooling

"""###**4. Remove duplicates**"""

df_literacy.drop_duplicates(inplace=True) # modify
df_literacy

df_illiteracy.drop_duplicates(inplace=True)
df_illiteracy

df_gdp_schooling.drop_duplicates(inplace=True)
df_gdp_schooling

"""###**5. Handle missing values: Drop or impute & reseting index**"""

# df_literacy
df_literacy.isnull().sum() # find null or missing values and count

cols = ["Code", "Region", "Male", "Female"] #impute null or missing value for better EDA

for col in cols:
    if col in ["Code", "Region"]:
        df_literacy[col] = df_literacy[col].fillna(
            df_literacy[col].mode()[0]
        ) # for str columns
    else:
        # numerical columns
        df_literacy[col] = df_literacy[col].fillna(
            df_literacy[col].median()
        )

print(df_literacy.isnull().sum()) # verification for missing values are imputed or not

df_literacy

# df_illiteracy
print(df_illiteracy.isnull().sum())

df_illiteracy["Code"] = df_illiteracy["Code"].fillna(df_illiteracy["Code"].mode()[0])

print(df_illiteracy.isnull().sum())

df_illiteracy

# df_gdp_schooling
df_gdp_schooling

print(df_gdp_schooling.isnull().sum())

columns = ['GDP', "Region", 'Avg_yrs_schooling', "Literacy", "Population"]

for c in columns:
    if c in ["Region"]:
        df_gdp_schooling[c] = df_gdp_schooling[c].fillna(df_gdp_schooling[c].mode()[0])
    else:
        df_gdp_schooling[c] = df_gdp_schooling[c].fillna(df_gdp_schooling[c].median())

print(df_gdp_schooling.isnull().sum())

df_gdp_schooling

"""###**6. Understand the shape and structure of the data**

**df_literacy**
"""

df_literacy.head()

df_literacy.info() # to quickly understand the structure and basic details of your dataset

df_literacy.shape # check how big is the data

df_literacy.dtypes # checking the data types of columns

df_literacy.describe() # To get the quick overview/snapshot of key summary statistics

"""**df_illiteracy**"""

# df_illiteracy
df_illiteracy.head()

df_illiteracy.info()

df_illiteracy.shape

df_illiteracy.dtypes

df_illiteracy.describe()

"""****df_gdp_schooling****"""

# df_gdp_schooling
df_gdp_schooling.head()

df_gdp_schooling.info()

df_gdp_schooling.shape

print(df_gdp_schooling.dtypes)

print(df_gdp_schooling.describe())

"""###**7. Filtering years between 1990 - 2023 (or last year in the data collected)**"""

df_literacy

# df_literacy
df_literacy = df_literacy[(df_literacy['Year'] >= 1990) & (df_literacy['Year'] <= 2023)]
df_literacy

# reset index after fillter data between 1990 to 2023
df_literacy = df_literacy.reset_index(drop=True)
df_literacy

# df_illitercy
df_illiteracy["Year"].min()

df_illiteracy["Year"].max()

# df_illiteracy
df_illiteracy = df_illiteracy[(df_illiteracy['Year'] >= 1990) & (df_illiteracy['Year'] <= 2023)]
df_illiteracy

df_illiteracy = df_illiteracy.reset_index(drop=True)
df_illiteracy

# df_gdp_schooling
df_gdp_schooling = df_gdp_schooling[(df_gdp_schooling['Year'] >= 1990) & (df_gdp_schooling['Year'] <= 2023)]
df_gdp_schooling

df_gdp_schooling = df_gdp_schooling.reset_index(drop=True)
df_gdp_schooling

df_gdp_schooling

"""#**Merge Population column to Litracy and Illiteracy DataFrame for EDA**"""

df_population = df_gdp_schooling[["Country", "Code", "Year", "Population"]].copy() #extract population column
df_population

# Lliteracy
df_literacy = pd.merge(df_literacy, df_population, on=["Country", "Code", "Year"], how = 'left') # merging for better eda
df_literacy

print(df_literacy.isnull().sum())

df_literacy["Population"] = df_literacy["Population"].fillna(df_literacy["Population"].median()) # imputing null for EDA

print(df_literacy.isnull().sum())

# Illiteracy
df_illiteracy = pd.merge(df_illiteracy, df_population, on=["Country", "Code", "Year"], how = 'left')
df_illiteracy

print(df_illiteracy.isnull().sum())

df_illiteracy["Population"] = df_illiteracy["Population"].fillna(df_illiteracy["Population"].median())

print(df_illiteracy.isnull().sum())
